# Generated by Django 2.1.15 on 2021-12-06 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_instrumentpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentpicture',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/'),
            preserve_default=False,
        ),
    ]
