# Generated by Django 2.1.15 on 2021-12-15 18:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruments', '0004_instrumentcmment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentCmment',
            new_name='InstrumentComment',
        ),
    ]
